### ISSUE TITLE
.NET 8 Todo List

### ISSUE THREAD

**Issue by rcdailey** [recyclarr/recyclarr#211]
When .NET 8 releases, during the .NET 8 upgrade the following items should be addressed.

- [x] Investigate using [AOT](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#native-aot-support) since it will obtain x64 and arm64 support for macOS.
- [x] `SpecialFolder.ApplicationData` path is changing ([docs](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix))
- [x] Review other [.NET 8 changes](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8)

**Comment by fabricionaweb** [comment]
Is it compatible with musl? Sorry if it is a silly question

**Comment by rcdailey** [comment]
> Is it compatible with musl? Sorry if it is a silly question

It's not a silly question at all. I'll need to wait until .NET 8 releases to be sure, but I don't think it'll be a problem. AOT compatibility is concerned with underlying architecture. MUSL itself is still linux, just a different implementation of libc. So I am not aware of any reason it should be an issue. But like I said, the checklist item above for AOT is more of a spike (investigation effort) rather than "do it".

AOT won't be compatible with 32-bit builds, but I can conditionally skip those.

Thanks for the great question!
