### ISSUE TITLE
v7.0 Todo List

### ISSUE THREAD

**Issue by rcdailey** [recyclarr/recyclarr#217]
The changes below should be made before the next major (v7) release. Most of these involve deletion/cleanup of backward compatibility code.

- [x] Migration Step: `DeleteRepoDirMigrationStep`
- [x] Migration Step: `MoveOsxAppDataDotnet8` and also remove backward compatibility logic in `DefaultAppDataSetup`.
- [x] Change default of `replace_existing_custom_formats` to `true`.
